### ISSUE TITLE
Elevator back to top button

### ISSUE THREAD

**Issue by ThePsionic** [hobinjk/XKit#101]
Just for fun, shits and giggles, incorporate the [wonderfulness that is Elevator.js](http://tholman.com/elevator.js/) to enjoy going back to the top of the page. This is of course entirely optional and has no effect on anything so I understand if you don't want to do this ;)

**Comment by Zarggg** [comment]
I've seen someone use an implementation of this with "Careless Whisper" and I just about died laughing.

Definitely an optional extension candidate, IMHO.

**Comment by hobinjk** [comment]
It's like you're inside my brain! This was one of the first ideas I had for an extension and I am happy to announce that Elevator v0.0.1 now exists. Someone should stop me before I make Piano Scroller happen.

**Comment by ThePsionic** [comment]
You are an amazing person and I love you, @hobinjk.
