### ISSUE TITLE
Go-To-Dash doesn't work on own blog

### ISSUE THREAD

**Issue by hobinjk** [hobinjk/XKit#50]
I believe that it doesn't display.

**Comment by karanguni** [comment]
I believe this is part of Go-To-Dash's spec - 

>  This extension adds a 'view' button on peoples blogs that allows you to go back to that post on your dashboard. This feature only works on the blogs you follow. If the post was made before you followed them, you might not see them on your dashboard when you click the view button.

That said, it does work for me, so maybe more information needed on how to replicate.

**Comment by nightpool** [comment]
@karanguni because your post appears on your own dashboard, it *should* theoretically work just fine. (and does under old xkit so any issue here is a regression)

**Comment by nightpool** [comment]
view-on-dashboard on my own blogs works fine for me.

**Comment by hobinjk** [comment]
Works for me on both Firefox and Chrome. Closing unless someone can reproduce.
