### ISSUE TITLE
Provide a Mutual/Unfollower Checker

### ISSUE THREAD

**Issue by hobinjk** [hobinjk/XKit#54]
At least one person wants this

**Comment by dlmarquis** [comment]
Someone mentioned something about this causing problems in the past --- people being banned by staff for using a similar function?

**Comment by Zarggg** [comment]
Many social networks dislike the idea of being able to see a specific report of people who unfollow a given user.

One thing to consider is that drawing attention to the fact that one user unfollowed another can provide an avenue for the unfollowed user to harass the unfollower.

**Comment by hobinjk** [comment]
Yeah, this seems like not an actually good thing to have. This is what I get for blindly copying asks
