### ISSUE TITLE
One Click Reblog doesn't give room to write

### ISSUE THREAD

**Issue by hobinjk** [hobinjk/XKit#61]
When selecting the open in new tab option the composition window that opens does not have a space to write in, forcing the user to mess with the editor to create it.

**Comment by realityfabric** [comment]
I could be wrong, I don't know jQuery so I couldn't follow everything that was going on, but could this be a problem with strip_sentence?
Line 1213:
`m_sentence = m_sentence.replace("<p></p>","");`

**Comment by hobinjk** [comment]
@realityfabric That seems like a logical explanation. If you want to test it, go to http://tumblr.com/xkit_editor (it's really nice in Firefox) and open one_click_reblog. There's also more information [here](https://github.com/hobinjk/XKit/wiki/Fixing-a-bug).

**Comment by realityfabric** [comment]
Well, it doesn't look like that was it, I completely removed that line and nothing changed.

**Comment by hobinjk** [comment]
Hmm, that's too bad. I'll try a less elegant fix.
