### ISSUE TITLE
Editable Reblog deletes text from edit post.

### ISSUE THREAD

**Issue by alextpedro** [hobinjk/XKit#67]
With the Editable Reblog extension enabled, text from edit post gets erased.

Disabled:
![er_disabled](https://cloud.githubusercontent.com/assets/5782944/8995927/830cde1c-370c-11e5-8142-73d057115f4a.png)

Enabled:
![er_enabled](https://cloud.githubusercontent.com/assets/5782944/8995928/830ed280-370c-11e5-93e3-d9fa3a70c288.png)

**Comment by hobinjk** [comment]
This should be fixed by Editable Reblogs v1.0.2. Thank you for reporting it!
