### ISSUE TITLE
Debugging on Firefox is sad

### ISSUE THREAD

**Issue by hobinjk** [hobinjk/XKit#69]
Because of the security enhancements in the addon-sdk, errors in XKit on Firefox don't get reported anywhere unless explicitly handled. While this will eventually be fixed in Firefox DevTools (I hope), a stopgap solution needs to exist.

**Comment by nightpool** [comment]
does this work if you enable addon debugging and open up the extension console.

**Comment by nightpool** [comment]
(the "Enable browser chrome and add-on debugging toolboxes" option)

**Comment by hobinjk** [comment]
In my experience, I've found that neither the add-on debugging console nor the browser chrome toolbox report errors made in the addon's content scripts (xkit.js and friends). That being said, I use Firefox Nightly, which has its own special set of weird behaviors.

**Comment by nightpool** [comment]
okay so this isn't nightly (its just mainline firefox) *and* I just ran it with jpn run (which is different in a few ways from a normal firefox startup but it's escaping me how right now) and logging is working fine:

![image](https://cloud.githubusercontent.com/assets/233815/8998478/7f11ac5c-36f3-11e5-930d-52585260cd60.png)

**Comment by hobinjk** [comment]
Oh cool! Thank you so much for pointing this out, I didn't think there were any solutions better than just alert()ing everywhere. I will close this issue and resume believing in the free web.

**Comment by karanguni** [comment]
Choose your own log level: https://blog.mozilla.org/addons/2013/03/27/changes-to-console-log-behaviour-in-sdk-1-14/

**Comment by WyohKnott** [comment]
Cf. https://developer.mozilla.org/en-US/Add-ons/SDK/Tools/console#Logging_Levels

For now you can add ```extensions.@new-xkit.sdk.console.logLevel``` to ```all``` in ```about:config```.

Otherwise, it could be added in the post-install script? Or create an option to set the debugging level of the extension in the ```Other``` panel menu (using this API https://developer.mozilla.org/en-US/Add-ons/SDK/Low-Level_APIs/preferences_service )
