### ISSUE TITLE
Receiving Error on Install

### ISSUE THREAD

**Issue by ospreysoul** [hobinjk/XKit#92]
I've tried installing on both Chrome and Firefox, and I receive the Code 100 and the Code 101 errors on them, respectively.
Firefox was a new, clean install, and I've uninstalled and reinstalled Chrome twice now, along with switching my Chrome profile and creating a new one.
![temp](https://cloud.githubusercontent.com/assets/13602881/9022802/7686ec82-3851-11e5-9463-3cd968b21398.jpg)

**Comment by ospreysoul** [comment]
![temp](https://cloud.githubusercontent.com/assets/13602881/9022807/99529054-3851-11e5-9652-819db67289f1.jpg)

**Comment by nightpool** [comment]
are you running behind some kind of proxy or firewall the prohibits you from contacting the xkit servers?

**Comment by ospreysoul** [comment]
I don't believe so. I've never set up a proxy, and I'm not aware of using one. As far as firewalls go, the only one active is the default Windows firewall. I was running Adblock Plus, but I uninstalled it from Chrome.
By the way, that link won't open for me—it says my connection timed out.

**Comment by nightpool** [comment]
Then I'm not sure what's going on, but something on your end. (maybe your
ISP?) is blocking you from reaching github.

**Comment by nightpool** [comment]
(just to confirm—you don't see anything at [this link](http://hobinjk.github.io/XKit/Extensions/dist/extensions.js)?)

**Comment by ospreysoul** [comment]
![temp](https://cloud.githubusercontent.com/assets/13602881/9023138/3ffbd64e-385d-11e5-8faf-e44d117763a5.jpg)
No, that page wouldn't load. Chrome's saying the connection timed out.

**Comment by nightpool** [comment]
can you see [this link](https://mozilla.github.io/)?

some filtering system is blocking your connections to github. are you in a school/work environment where some software like this may be in place?

**Comment by ospreysoul** [comment]
No, I'm actually on my own computer that I put together myself about a month ago. I've been looking everywhere to find out why github in particular seems to be partially blocked to me.

**Comment by hobinjk** [comment]
Something that might be worthwhile is checking your DNS configuration. I would especially think that this is the root of the issue if accessing other .io domains doesn't work. [https://crates.io/](https://crates.io/) should be up unless it's specifically github.io that is unreachable.

**Comment by ospreysoul** [comment]
That link works for me just fine. So, I guess it's github.io

**Comment by ospreysoul** [comment]
Finally got it to work today! I think my router simply needed to power cycle for a bit.
