### ISSUE TITLE
are we using the chrome management permission?

### ISSUE THREAD

**Issue by nightpool** [hobinjk/XKit#94]
![image](https://cloud.githubusercontent.com/assets/233815/9022933/5262bb72-384e-11e5-8aee-25b74d69a622.png)
I can't find any reference to it in bridge.js...

**Comment by hobinjk** [comment]
We are not. We're also not using the "tabs" permission. I've removed both of these and haven't noticed any decrease in functionality (which makes sense because the only things used are chrome.storage, chrome.runtime, and chrome.extension)
