### ISSUE TITLE
I can't install it ?

### ISSUE THREAD

**Issue by Raevik** [hobinjk/XKit#96]
Whenever I try to install it I get this message
![image](https://cloud.githubusercontent.com/assets/13604368/9023511/d3c5d1a4-389e-11e5-90c1-fd6869d44335.png)
I deactivated all proxies and it didn't work either so that's not the problem.
Can anyone please help me?

**Comment by nightpool** [comment]
this is a problem with the google web store, not xkit. you can read more
about it here
https://productforums.google.com/forum/#!topic/chrome/2AvdDgSJY08

**Comment by Raevik** [comment]
Thank you a lot I will
